/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ProjetoLocadoraVeiculos.gui;

import ProjetoLocadoraVeiculos.gui.cadastro.CadastroCarroGUI;
import ProjetoLocadoraVeiculos.gui.cadastro.CadastroClienteGUI;
import ProjetoLocadoraVeiculos.gui.cadastro.CadastroFabricanteGUI;
import ProjetoLocadoraVeiculos.gui.cadastro.CadastroModeloGUI;
import ProjetoLocadoraVeiculos.gui.cadastro.CadastroSeguradoraGUI;
import ProjetoLocadoraVeiculos.gui.cadastro.CadastroSeguradoraTelefoneGUI;

/**
 *
 * @author Riquetti
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        menuCadastro = new javax.swing.JMenu();
        menuCadastroFabricante = new javax.swing.JMenuItem();
        menuCadastroModelo = new javax.swing.JMenuItem();
        menuCarro = new javax.swing.JMenuItem();
        menuSeguradora = new javax.swing.JMenuItem();
        menuTelefoneSeguradora = new javax.swing.JMenuItem();
        menuCliente = new javax.swing.JMenuItem();
        Locacao = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuCadastro.setText("Cadastro");

        menuCadastroFabricante.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menuCadastroFabricante.setText("Fabricante");
        menuCadastroFabricante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastroFabricanteActionPerformed(evt);
            }
        });
        menuCadastro.add(menuCadastroFabricante);

        menuCadastroModelo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menuCadastroModelo.setText("Modelo");
        menuCadastroModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastroModeloActionPerformed(evt);
            }
        });
        menuCadastro.add(menuCadastroModelo);

        menuCarro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menuCarro.setText("Carro");
        menuCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCarroActionPerformed(evt);
            }
        });
        menuCadastro.add(menuCarro);

        menuSeguradora.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_4, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menuSeguradora.setText("Seguradora");
        menuSeguradora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSeguradoraActionPerformed(evt);
            }
        });
        menuCadastro.add(menuSeguradora);

        menuTelefoneSeguradora.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_5, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menuTelefoneSeguradora.setText("Telefone Seguradora");
        menuTelefoneSeguradora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTelefoneSeguradoraActionPerformed(evt);
            }
        });
        menuCadastro.add(menuTelefoneSeguradora);

        menuCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_6, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menuCliente.setText("Cliente");
        menuCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuClienteActionPerformed(evt);
            }
        });
        menuCadastro.add(menuCliente);

        jMenuBar1.add(menuCadastro);

        Locacao.setText("Locação");
        jMenuBar1.add(Locacao);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuCadastroFabricanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastroFabricanteActionPerformed
        CadastroFabricanteGUI dialog = new CadastroFabricanteGUI(this, true);
        dialog.setVisible(true);
    }//GEN-LAST:event_menuCadastroFabricanteActionPerformed

    private void menuCadastroModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastroModeloActionPerformed
        CadastroModeloGUI dialog = new CadastroModeloGUI(this, true);
        dialog.setVisible(true);
    }//GEN-LAST:event_menuCadastroModeloActionPerformed

    private void menuCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCarroActionPerformed
        CadastroCarroGUI dialog = new CadastroCarroGUI(this, true);
        dialog.setVisible(true);
    }//GEN-LAST:event_menuCarroActionPerformed

    private void menuSeguradoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSeguradoraActionPerformed
        CadastroSeguradoraGUI dialog = new CadastroSeguradoraGUI(this, true);
        dialog.setVisible(true);
    }//GEN-LAST:event_menuSeguradoraActionPerformed

    private void menuTelefoneSeguradoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTelefoneSeguradoraActionPerformed
        CadastroSeguradoraTelefoneGUI dialog = new CadastroSeguradoraTelefoneGUI(this, true);
        dialog.setVisible(true);
    }//GEN-LAST:event_menuTelefoneSeguradoraActionPerformed

    private void menuClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuClienteActionPerformed
        CadastroClienteGUI dialog = new CadastroClienteGUI(this, true);
        dialog.setVisible(true);
    }//GEN-LAST:event_menuClienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Locacao;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuCadastro;
    private javax.swing.JMenuItem menuCadastroFabricante;
    private javax.swing.JMenuItem menuCadastroModelo;
    private javax.swing.JMenuItem menuCarro;
    private javax.swing.JMenuItem menuCliente;
    private javax.swing.JMenuItem menuSeguradora;
    private javax.swing.JMenuItem menuTelefoneSeguradora;
    // End of variables declaration//GEN-END:variables
}
