/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ProjetoLocadoraVeiculos.gui.cadastro;

import ProjetoLocadoraVeiculos.dao.EstadoDAO;
import ProjetoLocadoraVeiculos.dao.MunicipioDAO;
import ProjetoLocadoraVeiculos.dao.SeguradoraDAO;
import ProjetoLocadoraVeiculos.entity.Estado;
import ProjetoLocadoraVeiculos.entity.Municipio;
import ProjetoLocadoraVeiculos.entity.Seguradora;
import java.util.List;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author Riquetti
 */
public class CadastroSeguradoraEditarGUI extends javax.swing.JDialog {

    private SeguradoraDAO dao = new SeguradoraDAO();
    private Seguradora seguradoraEditar = null;
    private CadastroSeguradoraGUI parentDialog;

    /**
     * Creates new form CadastroFabricanteEditarGUI
     */
    public CadastroSeguradoraEditarGUI(java.awt.Frame parent, boolean modal, CadastroSeguradoraGUI dialogParent) {
        super(parent, modal);
        parentDialog = dialogParent;

        initComponents();

        carregarComboEstado();
        carregarComboMunicipio();
    }

    public void carregarSeguradora(int id) {
        seguradoraEditar = dao.select(id);

        txtSeguradora.setText(String.valueOf(seguradoraEditar.getNome()));
        txtEmail.setText(String.valueOf(seguradoraEditar.getEmail()));
        txtCnpj.setText(String.valueOf(seguradoraEditar.getCnpj()));
        txtValorSeguro.setText(String.valueOf(seguradoraEditar.getValor()));

    }

    private void carregarComboEstado() {
        EstadoDAO dao = new EstadoDAO();
        List<Estado> listaEstado = dao.select();

        Object[] items = new Object[listaEstado.size()];

        int contador = 0;

        for (Estado estado : listaEstado) {
            items[contador] = estado;

            contador++;
        }

        ComboBoxModel model = new DefaultComboBoxModel(items);

        cboEstado.setModel(model);
        cboEstado.addActionListener((e) -> {
            carregarComboMunicipio();
        });
    }

    private void carregarComboMunicipio() {
        Estado estadoSelecionado = (Estado) cboEstado.getSelectedItem();
        if (estadoSelecionado != null) {
            int idEstado = estadoSelecionado.getId_estado();

            MunicipioDAO dao = new MunicipioDAO();
            List<Municipio> listaMunicipio = dao.selectEstadoMunicipio(idEstado);

            DefaultComboBoxModel<Municipio> model = new DefaultComboBoxModel<>();
            for (Municipio municipio : listaMunicipio) {
                model.addElement(municipio);
            }

            ((JComboBox) cboMunicipio).setModel(model);
        }
    }

    private void limparCampos() {
        txtCnpj.setText("");
        txtEmail.setText("");
        txtSeguradora.setText("");
        txtValorSeguro.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jMenuItem1 = new javax.swing.JMenuItem();
        lblMunicipio = new javax.swing.JLabel();
        cboMunicipio = new javax.swing.JComboBox<>();
        lblEstado = new javax.swing.JLabel();
        cboEstado = new javax.swing.JComboBox<>();
        lblCnpj = new javax.swing.JLabel();
        txtCnpj = new javax.swing.JTextField();
        lblValorSeguro = new javax.swing.JLabel();
        txtValorSeguro = new javax.swing.JTextField();
        lblSeguradora = new javax.swing.JLabel();
        txtSeguradora = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        btnFechar = new javax.swing.JButton();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblMunicipio.setText("Município");

        lblEstado.setText("Estado");

        lblCnpj.setText("CNPJ");

        lblValorSeguro.setText("Valor do Seguro");

        lblSeguradora.setText("Seguradora");

        lblEmail.setText("Email");

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSeguradora)
                            .addComponent(txtSeguradora, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEmail)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCnpj)
                            .addComponent(txtCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEstado)
                            .addComponent(cboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblValorSeguro)
                            .addComponent(txtValorSeguro, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMunicipio)
                            .addComponent(cboMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(btnSalvar)
                        .addGap(18, 18, 18)
                        .addComponent(btnFechar)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSeguradora)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSeguradora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblEmail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCnpj)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblValorSeguro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtValorSeguro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblMunicipio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cboMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblEstado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFechar)
                    .addComponent(btnSalvar))
                .addContainerGap(97, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnFecharActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if (seguradoraEditar == null) {

            Municipio municipioSelecionado = (Municipio) cboMunicipio.getModel().getSelectedItem();
            Estado estadoSelecionado = (Estado) cboEstado.getModel().getSelectedItem();

            String nome = txtSeguradora.getText();
            String cnpj = txtCnpj.getText();
            String email = txtEmail.getText();
            Double valor = Double.parseDouble(txtValorSeguro.getText());

            Integer id_municipio = municipioSelecionado.getId_municipio();
            Integer id_estado = estadoSelecionado.getId_estado();

            try {
                dao.insert(nome, cnpj, email, valor, id_municipio, id_estado);
                JOptionPane.showMessageDialog(this, "Modelo Inserido com Sucesso!", "SUCESS", JOptionPane.INFORMATION_MESSAGE);

                parentDialog.carregarLista();

                limparCampos();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }

        } else {

            Municipio municipioSelecionado = (Municipio) cboMunicipio.getModel().getSelectedItem();
            Estado estadoSelecionado = (Estado) cboEstado.getModel().getSelectedItem();

            String nome = txtSeguradora.getText();
            String cnpj = txtCnpj.getText();
            String email = txtEmail.getText();
            Double valor = Double.parseDouble(txtValorSeguro.getText());

            Integer id_municipio = municipioSelecionado.getId_municipio();
            Integer id_estado = estadoSelecionado.getId_estado();

            int id = seguradoraEditar.getId();

            try {
                dao.update(nome, cnpj, email, valor, id_municipio, id_estado, id);
                JOptionPane.showMessageDialog(this, "Seguradora Editada com Sucesso!", "SUCESS", JOptionPane.INFORMATION_MESSAGE);

                parentDialog.carregarLista();

                this.dispose();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }

        }

    }//GEN-LAST:event_btnSalvarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cboEstado;
    private javax.swing.JComboBox<String> cboMunicipio;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JLabel lblCnpj;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblMunicipio;
    private javax.swing.JLabel lblSeguradora;
    private javax.swing.JLabel lblValorSeguro;
    private javax.swing.JTextField txtCnpj;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtSeguradora;
    private javax.swing.JTextField txtValorSeguro;
    // End of variables declaration//GEN-END:variables
}
